# Generated by Django 6.0.5 on 2026-05-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(max_length=20)),
                ('to_stage', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.jobapplication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
